-- SQLite
SELECT * FROM DARBUOTOJAI;

SELECT GIMIMO_DATA FROM DARBUOTOJAI;

SELECT VARDAS, PAVARDĖ, PAREIGOS FROM DARBUOTOJAI;

SELECT DISTINCT SKYRIUS_PAVADINIMAS FROM DARBUOTOJAI;

SELECT * FROM DARBUOTOJAI WHERE SKYRIUS_PAVADINIMAS = "Gamybos";

SELECT PAREIGOS FROM DARBUOTOJAI WHERE VARDAS ="Giedrius";

SELECT * FROM DARBUOTOJAI WHERE GIMIMO_DATA = "1986-09-19";

SELECT VARDAS FROM DARBUOTOJAI WHERE PAVARDĖ = "Sabutis";

SELECT VARDAS, PAVARDĖ FROM DARBUOTOJAI WHERE PAREIGOS = "Programuotojas" AND SKYRIUS_PAVADINIMAS = "Gamybos";

INSERT INTO DARBUOTOJAI(VARDAS, PAVARDĖ, GIMIMO_DATA, PAREIGOS, SKYRIUS_PAVADINIMAS)
VALUES("Lina", "Vigricaitė", "1984-12-19", "Programuotoja", "Gamybos");

INSERT INTO DARBUOTOJAI(VARDAS, PAVARDĖ, GIMIMO_DATA)
VALUES("Lina", "Vigricaitė", "1984-12-19");

UPDATE DARBUOTOJAI SET PAREIGOS = "Programuotoja", SKYRIUS_PAVADINIMAS = "Gamybos" WHERE VARDAS = "Lina" AND PAVARDĖ = "Vigricaitė"; 

DELETE FROM DARBUOTOJAI WHERE GIMIMO_DATA = "1984-12-19";

INSERT INTO DARBUOTOJAI(PAVARDĖ, PAREIGOS)
VALUES("Antanaitis", "Programuotojas");

UPDATE DARBUOTOJAI SET PAREIGOS ="Testuotojas" WHERE PAVARDĖ = "Antanaitis";

SELECT count() from DARBUOTOJAI WHERE PAREIGOS = "Testuotojas";